baseURL = "https://yeguclu.github.io/"
languageCode = "en-us"
title = "yeguclu"
publishDir = "docs"
theme = "PaperMod"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  defaultTheme = "dark"
  disableThemeToggle = false

  [params.profileMode]
    enabled = true
    title = "Hey there!"
    subtitle = "I'm a fresh graduate with a B.S. in Electrical and Electronics Engineering from Middle East Technical University, specializing in Computer Area. My studies covered computer architecture, networks, operating systems, microprocessors, and data structures, alongside hands-on experience in FPGA design, VHDL/Verilog, ARM assembly, and embedded systems. During my time at university, I co-founded ODTU Blockchain, a leading student-run blockchain organization in Turkey that has become a recognized presence in the ecosystem.<br><br>Currently, I focus on high-performance systems and blockchain protocol engineering. I develop in Rust, C++, and Solidity with projects ranging from multi-million-msg/sec asynchronous relays to performant trading systems. My current interests include Ethereum execution clients, EVM internals, PBS, MEV strategies, low-latency networking, and game theory. My goal is to merge systems engineering experience with cutting-edge blockchain infrastructure, creating robust, efficient, and scalable tools for the decentralized future."
    imageUrl = "profile.jpg"       # place your image in /static/
    imageWidth = 160
    imageHeight = 160
    imageTitle = "yeguclu"

  [[params.socialIcons]]
    name = "twitter"
    url = "https://x.com/yeguclu0x"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/yeguclu"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "articles"
    name = "Articles"
    url = "/articles/"
    weight = 20
